// Code generated by proxy-generator. DO NOT EDIT.
package repository

import (
	"context"
	"server-template/internal/domain/entity"
	"server-template/internal/domain/repository"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

type UserRepositoryProxy struct {
	UserRepository repository.UserRepository
}
func (p *UserRepositoryProxy) Create(ctx context.Context, user *entity.User) (error) {
	tracer := otel.Tracer("quote-tracer")
	ctx, span := tracer.Start(ctx, "Create")
	defer span.End()

	err := p.UserRepository.Create(ctx, user)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}

	return err
}

func (p *UserRepositoryProxy) FindByEmail(ctx context.Context, email string) (*entity.User, error) {
	tracer := otel.Tracer("quote-tracer")
	ctx, span := tracer.Start(ctx, "FindByEmail")
	defer span.End()

	ret0, err := p.UserRepository.FindByEmail(ctx, email)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}

	return ret0, err
}

