-- DO NOT EDIT THIS FILE!!!
--
-- Generate by https://github.com/yanun0323/gem

-- +goose Up
CREATE TABLE IF NOT EXISTS `users` (
  `id` UUID DEFAULT gen_random_uuid(),
  `name` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `status` INTEGER NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE UNIQUE INDEX udx_email ON `users` (`email`);

-- +goose Down
DROP TABLE IF EXISTS `users`;


-- DO NOT EDIT THIS FILE!!!