-- DO NOT EDIT THIS FILE!!!
--
-- Generate by https://github.com/yanun0323/gem

-- +goose Up
CREATE TABLE IF NOT EXISTS `users` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `status` INTEGER NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
);

-- +goose Down
DROP TABLE IF EXISTS `users`;


-- DO NOT EDIT THIS FILE!!!